VERSION 0.8

all:
    BUILD +test \
        --BASE_IMAGE=docker:20.10.14-dind \
        --BASE_IMAGE=docker:20.10.15-dind \
        --BASE_IMAGE=docker:dind \
        --BASE_IMAGE=alpine:latest \
        --BASE_IMAGE=debian:stable \
        --BASE_IMAGE=debian:stable-slim \
        --BASE_IMAGE=ubuntu:latest \
        --BASE_IMAGE=amazonlinux:1 \
        --BASE_IMAGE=amazonlinux:2 \
        --BASE_IMAGE=earthbuild/dind:alpine-3.22-docker-28.3.3-r1 \
        --BASE_IMAGE=earthbuild/dind:ubuntu-20.04-docker-28.1.1-1 \
        --BASE_IMAGE=earthbuild/dind:ubuntu-24.04-docker-28.3.3-1

test:
    ARG --required BASE_IMAGE
    FROM $BASE_IMAGE
    WORKDIR /root
    COPY ./docker-compose.yml ./
    WITH DOCKER --compose docker-compose.yml
        RUN true
    END
